# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2dec36a983eadcca4d439f64ccdee1e5245ceef94aa98453abd75d6b5ad99bbc610d6daf616bfd29012e0383f9fb2c0e02956f1a4e79863a002a46e51753e1

test:
  secret_key_base: 8784e6dfc19bdfeb6c811c47718b94bd33ab26d08f9c27d9a03f7dd5348da853e2c157b48e9dd83131a44b32519131adcca16a30140b532c13f30bbcf97f940f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
